In [78]:
import numpy as np

In [79]:
mat = np.array([[1,2],[3,4]])
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [80]:
mat[1,1]

4

In [81]:
mat

array([[1, 2],
       [3, 4]])

In [82]:
mat.shape

(2, 2)

In [83]:
def det_2(arr):
    return arr[0,0] * arr[1,1] - arr[0,1] * arr[1,0]

In [84]:
det_2(mat)

-2

In [85]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
# np.delete(np.delete(mat2,0,axis=1),0,axis=0)
# np.delete(np.delete(mat2,1,axis=1),0,0)
# mat2.shape
mat2[0,:][1] = -2
mat2[0,:]

array([ 1, -2,  3])

In [126]:
np.delete(np.delete(mat2,1,axis=1),0,axis=0)

array([[4, 6],
       [7, 9]])

In [135]:
def det_3(arr):
    f = {}
    res = []
    sum = 0
    for i in range(arr.shape[0]):
        t = arr[0,:][i] * det_2(np.delete(np.delete(arr,i,axis=1),0,axis=0))
        f[arr[0,:][i]] = arr[0,:][i]*det_2(np.delete(np.delete(arr,i,axis=1),0,axis=0))
        sum += t
        res.append(t)
    return sum,res,f
        

In [136]:
det_3(mat2)

(-24, [-3, -12, -9], {1: -3, 2: -12, 3: -9})

In [137]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
np.linalg.det(mat2)

0.0